config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :interview_questions
  resources :interview_categories
  resources :reviews
  root to: "products#index" #index path
  resources :products, only: [:new, :create, :show] #for importing the json file
  get '/softs', to: 'products#all_software'
  get '/icategories', to: 'interview_categories#all_categories'
  get '/reviews_per_house/:sfthouse_id', to: 'reviews#reviews_per_house'
  get '/questions_per_category/:cat_id', to: 'interview_questions#interviews_per_cat'
  get '/jobs_accepted', to: 'jobs#jobs_accepted'
  get '/privacy', to: 'products#privacy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/interview_category.rb
class InterviewCategory < ApplicationRecord
end

app/controllers/interview_categories_controller.rb
class InterviewCategoriesController < ApplicationController
  before_action :set_interview_category, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "secret", password: "secret", except: [:create, :all_categories]

  # GET /interview_categories
  # GET /interview_categories.json
  def index
    @interview_categories = InterviewCategory.all
  end

  def all_categories
    @categories = InterviewCategory.all.order(:id)
    render json: @categories
  end

  # GET /interview_categories/1
  # GET /interview_categories/1.json
  def show
  end

  # GET /interview_categories/new
  def new
    @interview_category = InterviewCategory.new
  end

  # GET /interview_categories/1/edit
  def edit
  end

  # POST /interview_categories
  # POST /interview_categories.json
  def create
    @interview_category = InterviewCategory.new(interview_category_params)

    respond_to do |format|
      if @interview_category.save
        format.html { redirect_to @interview_category, notice: 'Interview category was successfully created.' }
        format.json { render :show, status: :created, location: @interview_category }
      else
        format.html { render :new }
        format.json { render json: @interview_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interview_categories/1
  # PATCH/PUT /interview_categories/1.json
  def update
    respond_to do |format|
      if @interview_category.update(interview_category_params)
        format.html { redirect_to @interview_category, notice: 'Interview category was successfully updated.' }
        format.json { render :show, status: :ok, location: @interview_category }
      else
        format.html { render :edit }
        format.json { render json: @interview_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interview_categories/1
  # DELETE /interview_categories/1.json
  def destroy
    @interview_category.destroy
    respond_to do |format|
      format.html { redirect_to interview_categories_url, notice: 'Interview category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interview_category
      @interview_category = InterviewCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interview_category_params
      params.require(:interview_category).permit(:title, :description)
    end
end

app/helpers/interview_categories_helper.rb
module InterviewCategoriesHelper
end

app/views/interview_categories/_form.html.erb
<%= simple_form_for(@interview_category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/interview_categories/edit.html.erb
<h1>Editing Interview Category</h1>

<%= render 'form', interview_category: @interview_category %>

<%= link_to 'Show', @interview_category %> |
<%= link_to 'Back', interview_categories_path %>

app/views/interview_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interview Categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interview_categories.each do |interview_category| %>
      <tr>
        <td><%= interview_category.title %></td>
        <td><%= interview_category.description %></td>
        <td><%= link_to 'Show', interview_category %></td>
        <td><%= link_to 'Edit', edit_interview_category_path(interview_category) %></td>
        <td><%= link_to 'Destroy', interview_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interview Category', new_interview_category_path %>

app/views/interview_categories/new.html.erb
<h1>New Interview Category</h1>

<%= render 'form', interview_category: @interview_category %>

<%= link_to 'Back', interview_categories_path %>

app/views/interview_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @interview_category.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @interview_category.description %>
</p>

<%= link_to 'Edit', edit_interview_category_path(@interview_category) %> |
<%= link_to 'Back', interview_categories_path %>