config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :interview_questions
  resources :interview_categories
  resources :reviews
  root to: "products#index" #index path
  resources :products, only: [:new, :create, :show] #for importing the json file
  get '/softs', to: 'products#all_software'
  get '/icategories', to: 'interview_categories#all_categories'
  get '/reviews_per_house/:sfthouse_id', to: 'reviews#reviews_per_house'
  get '/questions_per_category/:cat_id', to: 'interview_questions#interviews_per_cat'
  get '/jobs_accepted', to: 'jobs#jobs_accepted'
  get '/privacy', to: 'products#privacy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/interview_question.rb
class InterviewQuestion < ApplicationRecord
  belongs_to :interview_category
end

app/controllers/interview_questions_controller.rb
class InterviewQuestionsController < ApplicationController
  before_action :set_interview_question, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "secret", password: "secret", except: [:create, :interviews_per_cat]

  # GET /interview_questions
  # GET /interview_questions.json
  def index
    @interview_questions = InterviewQuestion.all
  end

  def interviews_per_cat
    @iq = InterviewQuestion.select('question as title, answer as content').where(interview_category_id: params[:cat_id])
    render json: @iq
  end

  # GET /interview_questions/1
  # GET /interview_questions/1.json
  def show
  end

  # GET /interview_questions/new
  def new
    @interview_question = InterviewQuestion.new
  end

  # GET /interview_questions/1/edit
  def edit
  end

  # POST /interview_questions
  # POST /interview_questions.json
  def create
    @interview_question = InterviewQuestion.new(interview_question_params)

    respond_to do |format|
      if @interview_question.save
        format.html { redirect_to @interview_question, notice: 'Interview question was successfully created.' }
        format.json { render :show, status: :created, location: @interview_question }
      else
        format.html { render :new }
        format.json { render json: @interview_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interview_questions/1
  # PATCH/PUT /interview_questions/1.json
  def update
    respond_to do |format|
      if @interview_question.update(interview_question_params)
        format.html { redirect_to @interview_question, notice: 'Interview question was successfully updated.' }
        format.json { render :show, status: :ok, location: @interview_question }
      else
        format.html { render :edit }
        format.json { render json: @interview_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interview_questions/1
  # DELETE /interview_questions/1.json
  def destroy
    @interview_question.destroy
    respond_to do |format|
      format.html { redirect_to interview_questions_url, notice: 'Interview question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interview_question
      @interview_question = InterviewQuestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interview_question_params
      params.require(:interview_question).permit(:question, :answer, :interview_category_id)
    end
end

app/helpers/interview_questions_helper.rb
module InterviewQuestionsHelper
end

app/views/interview_questions/_form.html.erb
<%= simple_form_for(@interview_question) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :question %>
    <%= f.input :answer %>
    <%= f.association :interview_category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/interview_questions/edit.html.erb
<h1>Editing Interview Question</h1>

<%= render 'form', interview_question: @interview_question %>

<%= link_to 'Show', @interview_question %> |
<%= link_to 'Back', interview_questions_path %>

app/views/interview_questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interview Questions</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th>Interview category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interview_questions.each do |interview_question| %>
      <tr>
        <td><%= interview_question.question %></td>
        <td><%= interview_question.answer %></td>
        <td><%= interview_question.interview_category %></td>
        <td><%= link_to 'Show', interview_question %></td>
        <td><%= link_to 'Edit', edit_interview_question_path(interview_question) %></td>
        <td><%= link_to 'Destroy', interview_question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interview Question', new_interview_question_path %>

app/views/interview_questions/new.html.erb
<h1>New Interview Question</h1>

<%= render 'form', interview_question: @interview_question %>

<%= link_to 'Back', interview_questions_path %>

app/views/interview_questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @interview_question.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @interview_question.answer %>
</p>

<p>
  <strong>Interview category:</strong>
  <%= @interview_question.interview_category %>
</p>

<%= link_to 'Edit', edit_interview_question_path(@interview_question) %> |
<%= link_to 'Back', interview_questions_path %>