config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :interview_questions
  resources :interview_categories
  resources :reviews
  root to: "products#index" #index path
  resources :products, only: [:new, :create, :show] #for importing the json file
  get '/softs', to: 'products#all_software'
  get '/icategories', to: 'interview_categories#all_categories'
  get '/reviews_per_house/:sfthouse_id', to: 'reviews#reviews_per_house'
  get '/questions_per_category/:cat_id', to: 'interview_questions#interviews_per_cat'
  get '/jobs_accepted', to: 'jobs#jobs_accepted'
  get '/privacy', to: 'products#privacy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  http_basic_authenticate_with name: "secret", password: "secret", except: [:create, :reviews_per_house]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  def reviews_per_house
    @reviews = Review.where(sfthouse_id: params[:sfthouse_id], accepted: true)
    render json: @reviews
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    review = Review.where("device_token = ? and created_at > ?", params[:device_token], 1.days.ago)
    if review.count > 0
      render json: {error: "Already contains data!"}
    else
      review2 = Review.where("device_token = ? and sfthouse_id = ?", params[:device_token], params[:sfthouse_id])
      if review2.count > 0
        render json: {error: "Already contains data!"}
      else
        @review = Review.create(title: params[:title], description: params[:description], rating: params[:rating], sfthouse_id: params[:sfthouse_id], device_token: params[:device_token])
        if @review.save
          render json: {success: "Saved!"}
        else
          render json: {error: "Not saved!"}
        end
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:title, :description, :rating, :sfthouse_id, :accepted)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for(@review) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :rating %>
    <%= f.check_box :accepted %>
    <%= f.association :sfthouse %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Rating</th>
      <th>Sfthouse</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.title %></td>
        <td><%= review.description %></td>
        <td><%= review.rating %></td>
        <td><%= review.sfthouse %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @review.description %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Sfthouse:</strong>
  <%= @review.sfthouse %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>